In [7]:
#!pip install setuptools==65.5.0
#!pip install stable-baselines3[extra]>=2.0.0a4
#!pip install gym=0.26.2
#!pip install --upgrade kaggle_environments

In [1]:
from CustomCNN import CustomCNN
from stable_baselines3 import PPO
from UtilsModule import play3times, create_model

Loading environment lux_ai_s2 failed: No module named 'vec_noise'


In [3]:
load=True

policyName = "CnnPolicy"
if load:
    model = PPO.load("ppo_v0")
else:
    model = create_model(CustomCNN, policyName, agents2=["random"])

In [4]:
from MyEnvironmentGymConnect4 import MyEnvironmentGymConnect4
def get_env():
    env_train = MyEnvironmentGymConnect4(["random"])
    from stable_baselines3.common.vec_env import (DummyVecEnv)
    env = DummyVecEnv([lambda: env_train])

In [5]:
from stable_baselines3.common.evaluation import evaluate_policy
def print_evaluation(model):
    mean_reward, std_reward = evaluate_policy(model, model.get_env(), n_eval_episodes=60)
    print(f"mean_reward={mean_reward:.2f} +/- {std_reward}")

In [31]:
learn_mode = True
#learn_mode = False
if learn_mode:
    for i in range(1):
        # Train agent
        model.learn(total_timesteps=20)
        # Save the model
        model.save(f"ppo_v{i}")
        # save net (if no need training more)
        policy = model.policy
        policy.save(f"ppo_policy_v{i}.pkl")
        print_evaluation(model)

agents_in_random_order: ['random', None]
Done. Reward:  -1
agents_in_random_order: [None, 'random']
Done. Reward:  -1
agents_in_random_order: [None, 'random']
Done. Reward:  -1
agents_in_random_order: ['random', None]
Done. Reward:  1
agents_in_random_order: [None, 'random']
Done. Reward:  -1
agents_in_random_order: ['random', None]
Done. Reward:  1
agents_in_random_order: [None, 'random']
Done. Reward:  1
agents_in_random_order: [None, 'random']
Done. Reward:  1
agents_in_random_order: [None, 'random']
Done. Reward:  1
agents_in_random_order: ['random', None]
Done. Reward:  -1
agents_in_random_order: ['random', None]
Done. Reward:  1
agents_in_random_order: [None, 'random']
Done. Reward:  -10
agents_in_random_order: ['random', None]
Done. Reward:  1
agents_in_random_order: ['random', None]
Done. Reward:  1
agents_in_random_order: ['random', None]
Done. Reward:  -1
agents_in_random_order: ['random', None]
Done. Reward:  -1
agents_in_random_order: ['random', None]
Done. Reward:  1
agent

In [11]:
from stable_baselines3.common.vec_env import (DummyVecEnv)

model1 = PPO.load("ppo_v1")
env_train = MyEnvironmentGymConnect4(["random"])
model1.env = DummyVecEnv([lambda: env_train])
learn_mode = True
#learn_mode = False
if learn_mode:
    for i in range(25):
        model1.learn(total_timesteps=50)
        print_evaluation(model1)
model1.save(f"ppo_v1")

Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
mean_reward=0.47 +/- 2.0440508160101873
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
mean_reward=0.61 +/- 1.5633502473746603
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
mean_reward=0.58 +/- 1.5548518408046157
Done. Reward:  -10
mean_reward=0.76 +/- 0.8047572087075742
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
mean_reward=0.96 +/- 0.5940681623525954
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Done. Reward:  -10
Do

In [10]:
model1.save(f"ppo_v1")

In [13]:
#saved_policy = PPO.policy_aliases[policyName].load("ppo_policy_v1.pkl")
#mean_reward, std_reward = evaluate_policy(saved_policy, model.get_env(), n_eval_episodes=10)
#print(f"mean_reward={mean_reward:.2f} +/- {std_reward}")

In [27]:
model1 = PPO.load("ppo_v19")
def model_to_agent(model):
    def agent_local(obs, config):
        print("---------")
        observation = np.array(obs['board']) \
            .reshape(1,6,7)
        action, _ = model.predict(observation, deterministic=True)
        
        print("action:", action.item())
        return action.item()
    return agent_local

def play_and_draw(model, agents2 = ["random"]):
    env_train = MyEnvironmentGymConnect4(agents2)
    from stable_baselines3.common.vec_env import (DummyVecEnv)
    env = DummyVecEnv([lambda: env_train])
    model_function=model_to_agent(model)
    print(model_function)
    play3times(model_function, model.get_env(), agent2 = "random")
print("env:", model1.get_env())
play_and_draw(model)

env: None
<function model_to_agent.<locals>.agent_local at 0x0000014E6F4F4A60>
[2]
[<function model_to_agent.<locals>.agent_local at 0x0000014E6F4F4A60>, 'random'] None ERROR 0 DONE
[[[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]]]
[2]
['random', <function model_to_agent.<locals>.agent_local at 0x0000014E6F4F4A60>] 0 DONE None ERROR
[[[0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0]]]


In [20]:
print(model.get_env())